### ISSUE TITLE
How to run generated code?

### ISSUE THREAD

**Issue by ashirviskas** [SilverWingedSeraph/evolve-sbrain#3]
I am new to rust so I am unsure how to run sbrain code on my windows machine. Could someone help me out?

Also, I have this code:
`+.(|}a{+!as+]z.!q&*d{&*s!m|.p!-!s^qm[]{p<+`

It should generate fibionacci sequence if given [9] as a parameter.

**Comment by NoraCodes** [comment]
Currently there is no standalone execution engine; you can make one easily
using the sbrain library, or wait a bit and I'll make one.

**Comment by NoraCodes** [comment]
I've created a simple interpreter. https://github.com/SilverWingedSeraph/sbic

**Comment by ashirviskas** [comment]
This is great, thank you!
